[tool.poetry]
name = "selenium-test"
version = "1.0.0"
description = ""
authors = ["https://github.com/Barabashka656"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
selenium = "^4.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
